# Variables contain directory/file and so on
GO_BUILD_DIR = ./bin/
WEBSITE_DIR = ./website/

GO_BINARY = ${GO_BUILD_DIR}/tirelease
WEBSITE_BINARY = ${WEBSITE_DIR}/build/

DOCKER_ADDRESS = hub.pingcap.net
DOCKER_NAME = yejunchen/tirelease
DOCKER_FILE = ./deployments/docker/Dockerfile
K8S_METADATA_NAME = tirelease
K8S_DEPLOYMENT_FILE = ./deployments/kubernetes/
TIRELEASE_MAIN_FILE = ./cmd/tirelease/*.go

# =============================================================================
# The following are common build commands
# =============================================================================
build: build.web build.server

clean:
	@rm -rf ${GO_BUILD_DIR}
	@rm -rf ${WEBSITE_BINARY}
	@echo "clear all temporary files and folders successful hahaha!"

run: clean build
	./${GO_BINARY}

build.web:
	cd ${WEBSITE_DIR} && \
	yarn install && \
	yarn build

build.server:
	go fmt ./... && \
	go build -o ${GO_BINARY} ${TIRELEASE_MAIN_FILE}

# =============================================================================
# The following are common deployment commands
# =============================================================================
docker:
	docker build -f ${DOCKER_FILE} -t ${DOCKER_NAME} .
	docker tag ${DOCKER_NAME}:latest ${DOCKER_ADDRESS}/${DOCKER_NAME}:latest
	docker push ${DOCKER_ADDRESS}/${DOCKER_NAME}:latest

docker.run:
	docker run -p 8080:8080 -t ${DOCKER_NAME}

k8s.init:
	kubectl apply -f ${K8S_DEPLOYMENT_FILE}/namespace.yaml
	kubectl apply -f ${K8S_DEPLOYMENT_FILE}/deployment.yaml
	kubectl apply -f ${K8S_DEPLOYMENT_FILE}/service.yaml
	kubectl apply -f ${K8S_DEPLOYMENT_FILE}/ingress.yaml
	@echo "k8s deploy project successful hahaha!"

k8s.update:
	kubectl rollout restart deployment/${K8S_METADATA_NAME} -n ${K8S_METADATA_NAME}

k8s.clean:
	kubectl delete all,ingress --all -n ${K8S_METADATA_NAME}
	@echo "k8s clean all resources successful hahaha!"

# =============================================================================
# Help documentation for commands
# =============================================================================
help:
	@echo "make build : build all binaries"
	@echo "make run : build all binaries and run"
	@echo "make clean : clear all temporary files and folders generated by the 'make build' or 'make run'"


.PHONY: build run clean help
.PHONY: build.web build.server docker docker.run k8s k8s.clean

