BUILD_DIR = ./bin
WEB_DIR = ./web/build/
TIRELEASE_BINARY = ${BUILD_DIR}/tirelease
DOCKER_NAME = tirelease

# -- The most frequent instructions are placed in the front position
all: build.web build.server

run: all
	./${TIRELEASE_BINARY}

clean:
	rm -rf ${WEB_DIR}
	rm -rf ${BUILD_DIR}

docker:
#	docker build -t ${DOCKER_NAME} .
#	docker run -p 8080:8080 -t ${DOCKER_NAME}
	@echo "docker image build & run successful"

# -- low-frequency operations in the background are put in the back position
build.web:
	cd web && \
	yarn install && \
	yarn build

build.server:
	go build -o ${TIRELEASE_BINARY} cmd/tirelease/*.go

help:
	@echo "make all : build all binaries for tirelease"
	@echo "make run : build all binaries for tirelease and run"
	@echo "make clean : clear all temporary files and folders generated by the 'make all' or 'make run'"


.PHONY: all run clean help
.PHONY: build.web build.server docker

