export const sampleData = [
  {
    Number: 30918,
    Title: "DATA RACE in the SessionVars.InRestrictedSQL",
    Url: "https://github.com/pingcap/tidb/issues/30918",
    CreatedAt: "2022-01-06T13:02:38Z",
    ClosedAt: "2022-01-06T13:02:38Z",
    Severity: "major",
    State: "OPEN",
    Type: "bug",
    Assignee: "ichn-hu",
    Labels: [
      "type/bug",
      "severity/major",
      "affects-5.4",
      "affects-5.3",
      "affects-5.2",
      "may-affects-5.1",
      "may-affects-5.0",
      "may-affects-4.0",
    ],
    Affects: {
      master: "yes",
      5.4: "yes",
      5.3: "no",
      5.2: "no",
      5.1: "unknown",
      5.0: "unknown",
      4.0: "unknown",
    },
    ClosedByPR: {
      Repository: "tidb",
      Number: 31058,
      Title: "session: fix data race in ParseWithParamsInternal",
      Url: "https://github.com/pingcap/tidb/pull/31058",
      State: "MERGED",
      MergeTarget: "master",
      MergedAt: "2022-01-06T13:02:37Z",
      Commit: "5cd37f00086b58dc6e5c60cade4989c31a8cb0a0",
      Refs: null,
    },
    CloserCherryPicked: [
      {
        Repository: "tidb",
        Number: 31401,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31401",
        State: "OPEN",
        MergeTarget: "release-5.3",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
      {
        Repository: "tidb",
        Number: 31402,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31402",
        State: "OPEN",
        MergeTarget: "release-5.4",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
    ],
  },
];
