const data = {
  Number: 30918,
  Title: "DATA RACE in the SessionVars.InRestrictedSQL",
  Url: "https://github.com/pingcap/tidb/issues/30918",
  CreatedAt: "2022-01-06T13:02:38Z",
  ClosedAt: "2022-01-06T13:02:38Z",
  Severity: "major",
  State: "OPEN",
  Type: "bug",
  Assignee: "ichn-hu",
  Labels: [
    "type/bug",
    "severity/major",
    "affects-5.4",
    "affects-5.3",
    "affects-5.2",
    "affects-5.1",
    "may-affects-4.0",
  ],
  Affects: [
    {
      Version: "master",
      Affect: "yes",
      PR: {
        Repository: "tidb",
        Number: 31058,
        Title: "session: fix data race in ParseWithParamsInternal",
        Url: "https://github.com/pingcap/tidb/pull/31058",
        State: "MERGED",
        MergeTarget: "master",
        MergedAt: "2022-01-06T13:02:37Z",
        Commit: "5cd37f00086b58dc6e5c60cade4989c31a8cb0a0",
        Refs: null,
      },
      Release: { BaseVersion: "master", TriageStatus: "accept" },
    },
    {
      Version: "5.4",
      Affect: "yes",
      PR: {
        Repository: "tidb",
        Number: 31401,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31401",
        State: "OPEN",
        MergeTarget: "release-5.3",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
      Release: { BaseVersion: "5.4", TriageStatus: "accept", Patch: "1" },
    },
    {
      Version: "5.3",
      Affect: "yes",
      PR: {
        Repository: "tidb",
        Number: 31402,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31402",
        State: "OPEN",
        MergeTarget: "release-5.4",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
      Release: { BaseVersion: "5.3", TriageStatus: "later", Patch: "2" },
    },
    {
      Version: "5.2",
      Affect: "yes",
      PR: {
        Repository: "tidb",
        Number: 31403,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31402",
        State: "OPEN",
        MergeTarget: "release-5.4",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
      Release: { BaseVersion: "5.2", TriageStatus: "won't-fix", Patch: "4" },
    },
    {
      Version: "5.1",
      Affect: "yes",
      PR: {
        Repository: "tidb",
        Number: 31404,
        Title: "planner: do not cache tableDual plan (#31386)",
        Url: "https://github.com/pingcap/tidb/pull/31402",
        State: "MERGED",
        MergeTarget: "release-5.4",
        MergedAt: "0001-01-01T00:00:00Z",
        Commit: "",
        Refs: null,
      },
      Release: { BaseVersion: "5.1", TriageStatus: "released", Patch: "1" },
    },
    { Version: "5.0", Affect: "no", PR: null, Release: null },
    {
      Version: "4.0",
      Affect: "unknown",
      Release: { BaseVersion: "4.0", TriageStatus: "unknown", Patch: "1" },
    },
  ],
  ReleaseInNext: [,],
};

export const sampleData = [data];
