const VersionTableColumns = [
    {
        field: 'id',
        headerName: 'ID',
        headerAlign: 'left',
        hide: true,
        align: 'left',
        editable: false,
        filterable: false,
        sortable: true,
    },
    {
        field: 'name',
        headerName: 'Name',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: true,
        sortable: true,
        minWidth: 120,
    },
    {
        field: 'type',
        headerName: 'Type',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: true,
        filterable: true,
        sortable: true,
        minWidth: 120,
    },
    {
        field: 'status',
        headerName: 'Status',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: true,
        sortable: true,
        minWidth: 120,
    },
    {
        field: 'create_time',
        headerName: 'CreateTime',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: false,
        sortable: true,
        minWidth: 160,
    },
    {
        field: 'update_time',
        headerName: 'UpdateTime',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: false,
        sortable: true,
        minWidth: 160,
    },
    {
        field: 'owner',
        headerName: 'Owner',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: true,
        filterable: true,
        sortable: false,
        minWidth: 120,
    },
    {
        field: 'repos',
        headerName: 'Repos',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: true,
        filterable: false,
        sortable: false,
        minWidth: 160,
    },
    {
        field: 'labels',
        headerName: 'Labels',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: true,
        filterable: false,
        sortable: false,
        minWidth: 160,
    },
    {
        field: 'plan_release_time',
        headerName: 'PlanReleaseTime',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: false,
        sortable: true,
        minWidth: 160,
    },
    {
        field: 'actual_release_time',
        headerName: 'ActualReleaseTime',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: false,
        filterable: false,
        sortable: true,
        minWidth: 160,
    },
    {
        field: 'description',
        headerName: 'Description',
        headerAlign: 'left',
        hide: false,
        align: 'left',
        editable: true,
        filterable: false,
        sortable: false,
        minWidth: 260,
    },
];

export default VersionTableColumns;
