package git

// ============================================================= Constants
var CrossReferencedEvent = "CrossReferencedEvent"
var CherryPickLabel = "cherry-pick-approved"
var NotCheryyPickLabel = "do-not-merge/cherry-pick-not-approved"
var LGT2Label = "status/LGT2"
var BugTypeLabel = "type/bug"
var AffectsLabel = "affects-%s"
var AffectsPrefixLabel = "affects-"
var MayAffectsLabel = "may-affects-%s"
var MayAffectsPrefixLabel = "may-affects-"
var SeverityLabel = "severity/"
var SeverityCriticalLabel = "severity/critical"
var SeverityMajorLabel = "severity/major"
var TypeLabel = "type/"
var MergeableStateMergeable = "mergeable"
var MergeableStateUnstable = "unstable"
var MergeableStateUnknown = "unknown"
var MergeRetryComment = "/merge"
var OpenStatus = "open"
var ReleaseBranchPrefix = "release-"
